baseURL = "/"
languageCode = "en-us"
title = "A Big Notes"
theme = "hugo-tailwind-journal"
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
    tag = "tags"

[params]
    author = "Gede Wahyu"
    avatar = "images/avatar.jpeg"
    description = "Simple notes, curated TIL"
    tagline = "Persistence Memory"

